### ISSUE TITLE
AOT & Angular-CLI throw errors using the base example, new one here

### ISSUE THREAD

**Issue by DennisSmolek** [cloudinary/cloudinary_angular#77]
We had a ton of issues related to missing parameters, bad constructors, etc. 

First was the `@injectable` which I detailed on #76.

The AOT example shows how to use rollUp but Angular pushes people to use the CLI. 

To use the CLI, you must include the scripts for cloudinary as a global. Inside `.angular-cli.json`

``` javascript
scripts:["../node_modules/cloudinary-core/cloudinary-core-shrinkwrap.js"]
```

This will insure that cloudinary is loaded into the global namespace. We used the shrinkwrap version because the lib needs lodash and the shrinkwrap version has the specific lodash bundled together.

Then in your `app.module`

``` javascript
// cloudinary.. order may be important with AOT
import { Cloudinary } from 'cloudinary-core/cloudinary-core-shrinkwrap';
import { CloudinaryModule, CloudinaryConfiguration } from '@cloudinary-angular';

const cloudConfig = {
  cloud_name: 'your-cloud'
};

const cloudinaryLib = {
  Cloudinary: Cloudinary
};

@NgModule({
  imports: [
          BrowserModule,
          BrowserAnimationsModule,
          CommonModule,
          FormsModule,
          CloudinaryModule.forRoot(cloudinaryLib, cloudConfig)
    ///rest of your code
```

This cleared all the errors and got everything to compile.. Hope it helps!

**Comment by RomainMarecat** [comment]
Hello ! I had the same issue with 

@angular/cli: 1.0.0-rc.2
node: 7.7.2
os: linux x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.9
@cloudinary/angular: ^2.1.1
cloudinary-core: ^2.2.0


I try all posibilities in my module :
Today the best solution is the last with 
`ng serve` works
`ng serve -aot` doesn't work. `EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'CloudinaryJQuery' of null`
`ng build -prod` doesn't work  `EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'CloudinaryJQuery' of null`
`ng build -aot` doesn't work `EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'CloudinaryJQuery' of null`

#UPDATE 1

```
import { Cloudinary } from 'cloudinary-core';
import { CloudinaryModule, CloudinaryConfiguration } from '@cloudinary/angular';
import { CloudinaryConfig } from './../../shared/cloudinary.config';

@NgModule({
  imports: [
    BrowserModule,
    CommonModule,
    FileUploadModule,
    CloudinaryModule.forRoot(Cloudinary, CloudinaryConfig),
  ]
})
export class UserModule {}
```

#UPDATE 2

```
import * as Cloudinary from 'cloudinary-core';
import { CloudinaryModule, CloudinaryConfiguration } from '@cloudinary/angular';
import { CloudinaryConfig } from './../../shared/cloudinary.config';

const cloudinaryLib = {
  Cloudinary: Cloudinary
};

@NgModule({
  imports: [
    BrowserModule,
    CommonModule,
    FileUploadModule,
    CloudinaryModule.forRoot(cloudinaryLib, CloudinaryConfig),
  ]
})
export class UserModule {}
```

#UPDATE 3

import Cloudinary from shrinkwrap doesn't works too :
`import { Cloudinary } from 'cloudinary-core/cloudinary-core-shrinkwrap';`

`ERROR in ~/src/app/admin/user/user.module.ts (14,28): Cannot find module 'cloudinary-core/cloudinary-core-shrinkwrap'.)`

#UPDATE 4

`
import * as Cloudinary from 'cloudinary-core';
import { CloudinaryModule, CloudinaryConfiguration, provideCloudinary } from '@cloudinary/angular';

const cloudinaryLib = {
  Cloudinary: Cloudinary
};

@NgModule({
  imports: [
    BrowserModule,
    CommonModule,
    FileUploadModule,
    CloudinaryModule.forRoot(cloudinaryLib, CloudinaryConfig),
  ]
})

export class UserModule {}`

`TypeError: cloudinaryJsLib.Cloudinary is not a constructor`

#UPDATE 5
```
// user.module.ts
import * as Cloudinary from 'cloudinary-core';
import { CloudinaryModule, CloudinaryConfiguration } from '@cloudinary/angular';
import { CloudinaryConfig } from './../../shared/cloudinary.config';

@NgModule({
  imports: [
    BrowserModule,
    CommonModule,
    FileUploadModule,
    CloudinaryModule.forRoot(Cloudinary, CloudinaryConfig),
  ]
})
export class UserModule {}
```
In .angular-cli :
```
"scripts": [
	"../node_modules/jquery/dist/jquery.js",
	"../node_modules/cloudinary-core/cloudinary-core-shrinkwrap.js",
],
```
I try to add in my packages.json typings like that with eitanp461's typings (https://github.com/cloudinary/cloudinary_js/pull/122/commits/714d27d15b7880d21f094bdc1f674d025e7389a7), but it doesn't work too :
```
{ 
  "dependencies": {
    ...
  },
  "typings": "src/cloudinary-core.d.ts"
}
```

**Comment by DennisSmolek** [comment]
My first suggestion is move to the 4.0 branch as it's the clearest difference between our deployments so I'm hesitant to drill down much farther..

**Comment by eitanp461** [comment]
@DennisSmolek, @RomainMarecat
We have released `cloudinary-core` with a type definition file, see https://github.com/cloudinary/cloudinary_js/releases/tag/2.3.0.

I updated the Angular CLI sample with the --aot flag and it works now.
Please close this issue if it is fixed in your use case, or add more details to it for further analysis.

**Comment by jlamarr22** [comment]
Just wanted to comment here to let people know how I solved this. I had been looking at how I was importing the Cloudinary module in my `app.module.ts`, but my issue was actually being caused by the Component that was using Cloudinary. My file `app.module.ts` is similar to @RomainMarecat's Update 5 example above. 

We were using angular CLI to build/serve the application with the `--prod` flag, [which does a lot of background stuff.](https://angular.io/guide/deployment#build-with---prod) I _assume_ this step was removing the Cloudinary module reference in my component for whatever reason, causing the `TypeError: cloudinaryJsLib.Cloudinary is not a constructor` or other similar error. So, instead of importing Cloudinary directly to this module, which is only necessary for the config anyway (cloud_name / upload_preset), I am directly using my environment variables that I used to set up the module.

The following code solves these errors:
`TypeError: Cannot read property 'CloudinaryJQuery' of null`
`TypeError: cloudinaryJsLib.Cloudinary is not a constructor`

**package.json** -- Angular 4, Angular CLI 1.4.5, Cloudinary 4, and ng-file-upload 1.3.0:
```
{
  // Other stuff
  "scripts": {
    // Scripts
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.4.4",
    "@angular/cdk": "2.0.0-beta.12",
    "@angular/common": "^4.4.4",
    "@angular/compiler": "^4.4.4",
    "@angular/core": "^4.4.4",
    "@angular/flex-layout": "^2.0.0-beta.9",
    "@angular/forms": "^4.4.4",
    "@angular/http": "^4.4.4",
    "@angular/material": "2.0.0-beta.12",
    "@angular/platform-browser": "^4.4.4",
    "@angular/platform-browser-dynamic": "^4.4.4",
    "@angular/router": "^4.4.4",
    "@cloudinary/angular-4.x": "^1.1.0",
    "@types/lodash": "^4.14.77",
    "angular2-jwt": "^0.2.3",
    "auth0-js": "^8.11.2",
    "cloudinary-core": "^2.3.0",
    "core-js": "^2.5.1",
    "hammerjs": "^2.0.8",
    "intl": "^1.2.5",
    "lodash": "^4.17.4",
    "ng2-file-upload": "^1.3.0",
    "rxjs": "5.5.2",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.5",
    "@angular/compiler-cli": "^4.4.4",
    "@angular/language-service": "^4.4.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.5.3"
  }
}
```

**app.module.ts**:
```
import { NgModule} from '@angular/core';
// Other imports
import { CloudinaryModule } from '@cloudinary/angular-4.x';
import * as Cloudinary from 'cloudinary-core';

import { environment } from 'environments/environment';

@NgModule({
  declarations: [
    // Declarations
  ],
  imports: [
    // Other imports
    CloudinaryModule.forRoot(Cloudinary, environment.cloudinary.upload)
  ],
  providers: [
    // Other providers
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**environment.ts**:
```
export const environment = {
  // Other environment variables
  cloudinary: {
    upload: {
      cloud_name: 'test', // Your cloud name
      upload_preset: 'test_preset' // Your preset
    },
    baseApiUrl: 'https://api.cloudinary.com/v1_1/',
    // Other configuration stuff necessary for cloudinary
  }
};
```

**Component using Cloudinary**:
```
import { Component, OnInit, Input, Injectable } from '@angular/core';
import { FileUploader, FileUploaderOptions, ParsedResponseHeaders } from 'ng2-file-upload';
// Other imports

import { environment } from 'environments/environment';

@Component({
  selector: 'cloudinary-upload',
  templateUrl: 'cloudinary-upload.component.html',
  styleUrls: ['cloudinary-upload.component.scss']
})

@Injectable()
export class CloudinaryUploadComponent implements OnInit {
  uploader: FileUploader;

  constructor(/* Injections */) { }

  ngOnInit(): void {
    this.setupUploader();
  }

  private setupUploader() {
    const uploaderOptions: FileUploaderOptions = {
      url: `${environment.cloudinary.baseApiUrl}${environment.cloudinary.upload.cloud_name}/upload`,
      autoUpload: true,
      headers: [
        {
          name: 'X-Requested-With',
          value: 'XMLHttpRequest'
        }
      ]
    };
    this.uploader = new FileUploader(uploaderOptions);

    this.uploader.onBuildItemForm = (fileItem: any, form: FormData): any => {
      form.append('upload_preset', environment.cloudinary.upload.upload_preset);
      form.append('file', fileItem);

      fileItem.withCredentials = false;
      return { fileItem, form };
    };

    this.uploader.onCompleteItem = (item: any, response: string, status: number, headers: ParsedResponseHeaders) => {
      var parsed_response = JSON.parse(response);
      // Do something with the response
    }
  }
}
```

**Comment by lujakob** [comment]
For me a downgrade to 
`    "cloudinary-core": "^2.3.0",
`
solved it the 
`TypeError: Cannot read property 'CloudinaryJQuery' of null
`

**Comment by asafp** [comment]
still having this issue after downgrading to 2.3.0
did any one solved this ?

**Comment by eitanp461** [comment]
@asafp You can find sample projects that implement the required setup for each Angular version.
Does https://github.com/cloudinary/cloudinary_angular/tree/angular-2.x/samples/angular-cli-sample help you?

**Comment by mrkhangtran** [comment]
For anyone still looking for the solutions, it is here 
https://github.com/cloudinary/cloudinary_angular/tree/master/samples/angular-cli-sample

**Comment by inidaname** [comment]
For Angular 6 this is still an issue and I have tried every work around provided here and implemented some myself still no success please, I need your assistance

**Comment by strausr** [comment]
@inidaname Can you please provide more information on your implementation? perhaps a live example?

**Comment by uded** [comment]
I believe this is still a problem - did everything exactly as in the given CLI based example and I have same problem.

In my case it's Angular 7.2.x and latest Cloudinary libraries

**Comment by strausr** [comment]
@uded Can you please share with us the error you're seeing?
